### ISSUE TITLE
Pokemon Go won't connect behind a proxy

### ISSUE THREAD

**Issue by btimo** [justinleewells/pogo-optimizer#209]
Hey, 

just downloaded the last update of PokemonGo and it looks like they won't let you connect in the game when using pogo-optimizer.

I'm logging in without trouble when I don't proxy my connection through pogo optimizer. But as soon as I set up the proxy on my phone, the game connection is blocked.

Can someone confirm ?

**Comment by BlackPornActor** [comment]
Fock, I thought I was the only one.  Can confirm it.

**Comment by justinleewells** [comment]
It's still working fine for me. Try updating your cert if you pulled a new Docker container.

**Comment by btimo** [comment]
I'm on osx and not using docker.

I did try updating my cert but no change.

My version of Pokemon Go is 0.31.0

**Comment by justinleewells** [comment]
As soon as the update is added to the app store I'll check myself. This may be the end of the project. We'll have to wait and see.

**Comment by btimo** [comment]
You can get the apk here : https://apkpure.com/pok%C3%A9mon-go/com.nianticlabs.pokemongo

**Comment by justinleewells** [comment]
I use an iPhone, so I'll have to wait until it's added there.

**Comment by ChristRespawns** [comment]
Unfortunate FYI: [API Abuse Enforcement](https://fevgames.net/pokemon-go-apk-teardown-0-31-0/)

"Yesterday we saw requests throttled. A good analogy for this is replacing a double swinging door with a single door. Both doors allow traffic but one does in smaller amounts. For those who simply play the game, this means nothing to you. For those who run scripts and/or view Pokémon maps you might notice those being slow and/or not available.
Additionally, we saw the addition of SSL Pinning. The NianticTrustManager was added which enforces that a valid SSL certificate is used when talking with Niantic’s servers. What does this mean for you? No longer can you use a bogus certificate in order to inspect/watch traffic while the app runs. The common use case for this lately has been IV checkers and Poke scanners. Those were technically against the Terms of Service, so now breaking the ToS has been made a bit harder.
nativeCheckClientTrusted
nativeCheckServerTrusted
getAcceptedIssuers
Above is the name of 3 new functions added which explain the enforcement of trusted certificates on both client and server. We talked about the grey line you walk using applications that leverage the internal API and Niantic has taken the first step to stop these applications."

**Comment by justinleewells** [comment]
Well, that's it. They've blocked the app. I'll update the README to reflect the stopping of development. It's been fun working on this with everyone.

**Comment by dorian-marchal** [comment]
@justinleewells Can you add the message at the very top of the README ?

**Comment by dorian-marchal** [comment]
BTW, is this issue unresolvable ?

**Comment by macmanchomp** [comment]
Resolving it would be very difficult at best. Unless someone could use the
actual certificate they use I'm guessing you couldn't get a solid
connection through, but needless to say this is stupid. They completely
removed the nearby list's ability to function and have hidden values that
you cannot find within the app. Believe it or not a local mitm proxy would
have been able to restore the broken nearby list before. But instead of
fixing it they removed it. What jerks.

**Comment by deadowl** [comment]
If you root your device, it's likely that you can get around it, but it's a pretty clear message that they don't want projects like this one.

**Comment by macmanchomp** [comment]
Maybe, but you need a root hider cuz pogo will go nuts if it detects
something.

**Comment by justinleewells** [comment]
There are almost certainly ways around it, but like machmanchomp said, they clearly don't want us to do it and I'd feel unethical if I continued the project.
