### ISSUE TITLE
No Internet on iPhone after setting the Proxy

### ISSUE THREAD

**Issue by MarioDiar** [justinleewells/pogo-optimizer#74]
After I set the proxy in my iPhone (having already installed the certificate in the iphone correctly) and having both the mitm proxy server and frontend server running. I can't log in to the Pokemon Go application using Wi-Fi, if I use LTE I can connect normally. 

*Having done more tests, when I have the proxy on the phone active, I don't have internet via Wi-Fi at all.

Any ideas of what is going on?

**Comment by justinleewells** [comment]
Are you positive that you entered the correct ip address for the proxy?

**Comment by MarioDiar** [comment]
Yes I am pretty sure I did. It is really weird, any ideas of what could be happening?

**Comment by Lorkster** [comment]
I had the exact same issue. Apparently IOS has problems when it comes to quite a bit of network code (I've encountered issues like it in other scenarios). Some random combination of hard reboots and entering the proxy address finally got it to work for me. After it worked once, it's worked constantly since.

Sadly I have no step by step solution, since I really didn't do anything aside from reboots and entering the proxy again and again. :/

**Comment by jordansmellie** [comment]
It's not just iOS- I now have the same issue on Android. When I first installed Optimizer (I'm pretty sure it was 1.0.0) and got it all set up, all my traffic from my phone went through the proxy with no issues except being a bit slow. I could see all the server requests in the Terminal, though.

When I was trying to figure out how to pull 1.1.0 earlier today, I broke some things and wound up uninstalling a number of things and doing them over from scratch. I generated and installed a new CA certificate as part of that process, just like in the initial install. While Optimizer 1.1.0 is now running as written, I no longer see ANY server/traffic requests in the Terminal, and PoGo is the only application that manages to connect to the internet. All other apps on my phone show that they have no connection.

I'm not going to mess with it because it's only a slight inconvenience for me right now, but I wanted to mention that this is not limited to iOS devices.

I'm on Android 6.0.1, June security patch, running stock on a Nexus 5.

**Comment by justinleewells** [comment]
Not being able to use other apps is pretty annoying, but it's probably just a side-effect of the proxy. I'm not sure how we'd remedy that.

As of a couple versions ago, the pokemon-go-mitm library no longer logs traffic, so that's not a particularly good indicator of a problem.

**Comment by MarioDiar** [comment]
It's working for me now. I installed from the latest commit and it works.

**Comment by realbunny** [comment]
Im getting the same problem now, i can access hostip:3000 on my phone, and i have downloaded the certificate. But after setting up the proxy with the IP (I even check on my router what it was) and entered 8081 on port. I dont have any access to the internett, besides hostip:3000.
